spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 928158375038-qbbbq09rc9sdo6bi3aa2pndgs6e1fld5.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile